services:
  backend:
    build: ./app
    command: gunicorn ikassa.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    env_file:
      - ./.env
    expose:
      - '8000'
  nginx:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    ports:
        - 80:80/tcp
        - 443:443/tcp
    environment:
        CERTBOT_EMAIL: ikassa@main.com
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
volumes:
  static_volume:
  media_volume:
  letsencrypt: